### ISSUE TITLE
continuous improvement StoreFront Application

### ISSUE THREAD

**Issue by MiroBenicio** [mytiki/roadmap#4]
### Description

We should improve the current shape of storefront application, reviewing and cleaning the code.

Also, the API Spec and Deploy structure should be defined and start the development in some points.

### Milestones

- [ ] https://github.com/mytiki/platform-mon-storefront/milestone/1

### Acceptance Criteria

- [ ] Code reviewed and cleaned
- [ ] API Spec and JSONs created/updated
- [ ] Deploy Infrastructure defined
